In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.sample(5)

    age  gender review education purchased
43   27    Male   Poor        PG        No
41   23    Male   Good        PG       Yes
38   45  Female   Good    School        No
39   76    Male   Poor        PG        No
6    18    Male   Good    School        No

In [4]:
df = df.iloc[:,2:]

In [5]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [6]:
from sklearn.preprocessing import OrdinalEncoder

In [7]:
X_train

NameError: name 'X_train' is not defined

In [ ]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [ ]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [ ]:
X_train = oe.transform(X_train)

In [ ]:
X_train

array([[0., 1.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [2., 0.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [1., 2.],
       [2., 2.],
       [1., 1.],
       [1., 2.],
       [0., 2.],
       [0., 1.],
       [2., 2.],
       [1., 1.],
       [1., 2.],
       [2., 1.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [0., 0.],
       [0., 1.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [2., 1.]])

In [ ]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [ ]:
X_train

array([[1., 2.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [0., 0.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [2., 2.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [1., 2.],
       [2., 1.],
       [1., 0.],
       [2., 0.]])

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
le.fit(y_train)

LabelEncoder()

In [ ]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [ ]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [ ]:
y_train

array([1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1])